name: Run Hirose Coffee Notebook

on:
  schedule:
    - cron: '10 9 * * *'  # 毎日18:10（JST）
  workflow_dispatch:

env:
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install papermill jupyter requests selenium webdriver-manager beautifulsoup4 pytz

      - name: Run Hirose Coffee Notebook
        run: |
          papermill "廣瀬珈琲店スクレイピング.ipynb" "output_廣瀬珈琲店スクレイピング.ipynb" \
            -p SUPABASE_API_KEY "$SUPABASE_API_KEY"
