name: Run Sagano Yu Notebook

on:
  schedule:
    - cron: '20 9 * * *'  # 毎日18:20（JST）
  workflow_dispatch:

env:
  SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install papermill jupyter requests selenium webdriver-manager beautifulsoup4 pytz

      - name: Run Sagano Yu Notebook
        run: |
          papermill "スクレイピング統合-嵯峨野湯.ipynb" "output_スクレイピング統合-嵯峨野湯.ipynb" \
            -p SUPABASE_API_KEY "$SUPABASE_API_KEY"
